global:
  scrape_interval: 15s
  evaluation_interval: 15s

# No rule files are configured by default
rule_files: []

scrape_configs:
  # Webtop metrics (enable /metrics on port 80 to use)
  - job_name: 'webtop'
    static_configs:
      - targets: ['webtop:80']
    metrics_path: /metrics
    scrape_interval: 30s

  # Monitor Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana metrics (requires GF_METRICS_ENABLED=true)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics

# Alerting configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Remote write configuration (optional, for external monitoring)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"
